### ISSUE TITLE
Cannot use in direct boot mode

### ISSUE THREAD

**Issue by varis-m** [DataDog/dd-sdk-android#854] opened 2022-02-23 23:17 UTC
**Describe what happened**
crash with exception

    java.lang.RuntimeException: Unable to get provider androidx.work.impl.WorkManagerInitializer: java.lang.IllegalStateException: Cannot initialize WorkManager in direct boot mode
        at android.app.ActivityThread.installProvider(ActivityThread.java:7288)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6824)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
        at android.app.ActivityThread.access$1300(ActivityThread.java:238)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: java.lang.IllegalStateException: Cannot initialize WorkManager in direct boot mode
        at androidx.work.impl.WorkManagerImpl.internalInit(WorkManagerImpl.java:727)
        at androidx.work.impl.WorkManagerImpl.<init>(WorkManagerImpl.java:269)
        at androidx.work.impl.WorkManagerImpl.<init>(WorkManagerImpl.java:233)
        at androidx.work.impl.WorkManagerImpl.<init>(WorkManagerImpl.java:211)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:190)
        at androidx.work.WorkManager.initialize(WorkManager.java:210)
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7283)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6824) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:238) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7701) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 

**Steps to reproduce the issue:**
create an app with direct boot mode support
https://developer.android.com/training/articles/direct-boot

add  dependency "com.datadoghq:dd-sdk-android:1.11.0" to project and run project

**Describe what you expected:**
no crash

**Additional context**
 - Android OS version: android 11
 - Device Model:
 - Datadog SDK version:
 - Versions of any other relevant dependencies (OkHttp, …): 
 - Proguard configuration: 
 - Gradle Plugins:

**Comment by xgouchet** [comment] 2022-02-24 08:47
Hi @varis-m , thanks for submitting this issue, we'll investigate this and try and come up with a solution as soon as possible.

**Comment by xgouchet** [comment] 2022-03-03 07:26
Hi @varis-m , we aren't able to reproduce this particular issue. Do you have a code sample and steps to reproduce this crash?

**Comment by xgouchet** [comment] 2022-03-21 08:15
Since we didn't get any response helping us to reproduce this issue, we're closing it for now. Feel free to reopen it with more details.

**Closed by xgouchet** 2022-03-21 08:15 UTC
Labels: bug, waiting-for-info
