### ISSUE TITLE
Crash when click openOptionsMenu

### ISSUE THREAD

**Issue by nikeshbhawsar** [DataDog/dd-sdk-android#545] opened 2021-03-24 12:05 UTC
Thanks for taking the time for reporting an issue!

**Describe what happened**
Application crashes on _openOptionsMenu_ click event.

If I remove _useViewTrackingStrategy_ in _Configuration_ it works well.

**Crash Logs:**
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p1
        at com.datadog.android.rum.internal.instrumentation.gestures.WindowCallbackWrapper.onMenuOpened(Unknown Source:2)
        at com.android.internal.policy.PhoneWindow.openPanel(PhoneWindow.java:846)
        at com.android.internal.policy.PhoneWindow.openPanel(PhoneWindow.java:818)
        at android.app.Activity.openOptionsMenu(Activity.java:3922)
        at com.wm.ocs.android.da.view.AbstractDriverActivity.onClickAction(AbstractDriverActivity.java:1055)
        at com.wm.ocs.android.da.DriverActivity.onClickAction(DriverActivity.java:908)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6087) 
        at android.view.View.performClick(View.java:7368) 
        at android.view.View.performClickInternal(View.java:7334) 
        at android.view.View.access$3200(View.java:849) 
        at android.view.View$PerformClick.run(View.java:27906) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7285) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 

**Steps to reproduce the issue:**
call _**openOptionsMenu**_ in Activity
**Describe what you expected:**
it should work while using openOptionsMenu()
**Additional context**
 - Android OS version: 9
 - Device Model: Samsung SM-T307U
 - Datadog SDK version: 1.8.1
 - Versions of any other relevant dependencies (OkHttp, …): 
     -- androidx.appcompat:appcompat:1.2.0 
 - Proguard configuration:  default configuration
 - Gradle Plugins:
    -- android gradle : 4.1.0
    -- minSdkVersion 23
    -- compileSdkVersion 29
    -- Activity is subclass of FragmentActivity

**Comment by xgouchet** [comment] 2021-03-25 09:47
Hi @nikeshbhawsar,
This is really similar to the issue #492, which should be solved when using `androidx.appcompat:appcompat:1.2.0`. 
Can you share what your menu XML file looks like?  Also can you confirm that the version of `androidx.appcompat:appcompat` resolved by Gradle is indeed `1.2.0`?

**Comment by nikeshbhawsar** [comment] 2021-03-25 10:34
I checked  issue #492 but it looks different.
androidx.appcompat:appcompat version is 1.2.0 only below is the resolved library screenshot.

![image](https://user-images.githubusercontent.com/13655104/112458926-4f8ffa00-8d83-11eb-9b0f-8f41870ae8e8.png)

Menu XML:
```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:id="@+id/menu_exit" android:title="@string/menu_opt_exit" android:icon="@drawable/ic_menu_exit"/>
    <item android:id="@+id/menu_system" android:title="@string/menu_opt_system" android:icon="@drawable/ic_menu_preferences" />
    <item android:id="@+id/menu_sys_location_info" android:title="@string/menu_opt_sys_location_info" android:icon="@drawable/ic_menu_sys_location_info" android:visible="false"/>
    <item android:id="@+id/menu_theme_mode" android:title="@string/menu_opt_theme_mode" android:icon="@android:drawable/btn_star_big_off" android:visible="false" />
	<item android:id="@+id/menu_route_overview" android:title="@string/menu_opt_route_overview" android:icon="@drawable/ic_menu_show_route"/>
    <item android:id="@+id/menu_brightness" android:title="@string/menu_opt_display" android:icon="@drawable/ic_menu_display" />
    <!-- Hide the about menu option for now, until we get approval from the business to include it in DA -->
    <item android:id="@+id/menu_about" android:title="@string/menu_opt_about" android:icon="@drawable/ic_menu_system_info" android:visible="false"/>
    <item android:id="@+id/menu_driver_safety_form" android:title="@string/menu_opt_safety_form" android:icon="@drawable/ic_menu_safety_form" android:visible="false"/>
    <item android:id="@+id/menu_demo_readme" android:title="@string/menu_opt_demo_readme" android:icon="@drawable/ic_menu_read_me" android:visible="false"/>
    <item android:id="@+id/menu_compliance" android:title="@string/compliance" android:icon="@drawable/ic_menu_cc"/>
     <item android:id="@+id/menu_dvir" android:title="@string/dvir" android:icon="@drawable/ic_menu_open_dvir"/>
    <item android:id="@+id/menu_cancel" android:title="@string/cancel" android:icon="@drawable/ic_menu_cancel"/>
</menu>
```

**Comment by xgouchet** [comment] 2021-03-25 11:41
Hi @nikeshbhawsar , 
The issue I linked has the same stacktrace and behavior, which is why I think it's related.
I couldn't reproduce this issue with the given menu. Could you share share your `build.gradle` file  to see if I can spot any difference with my own?

**Comment by nikeshbhawsar** [comment] 2021-03-25 14:30
Hi @xgouchet, Please find the gradle build file.

[build-gradle.txt](https://github.com/DataDog/dd-sdk-android/files/6205430/build-gradle.txt)

**Comment by xgouchet** [comment] 2021-04-08 12:51
Hey @nikeshbhawsar, we can't reproduce this issue on our end. Can you reproduce it with your own application ? If so, can you share with us a sample code to let us understand this issue ?
If you can't share your code with us, we could schedule a call to debug this remotely.
From our understanding, this is most likely an issue in the Android OS itself, since the signature of the `Window.Callback.onMenuOpened` explicitly expects a non null argument.

**Comment by xgouchet** [comment] 2021-04-08 13:45
Hey @nikeshbhawsar 
I managed to reproduce this in a short sample, and I can confirm that the issue lies within Android's `PhoneWindow` class, in their implementation of the `openPanel()` method which is called by `openOptionsMenu`.
Unfortunately, because we're using Kotlin, we can't really do anything about it: we implement an interface that expect a non `null` menu object, but the `PhoneWindow` calls it with a null argument. 

I opened a ticket in the Android framework to solve this here : https://issuetracker.google.com/issues/184760938

**Closed** 2021-07-27 07:12 UTC
Labels: bug
