### ISSUE TITLE
App crash on RUM

### ISSUE THREAD

**Issue by MohammadRezaei92** [DataDog/dd-sdk-android#455] opened 2020-12-29 17:07 UTC
```
Fatal Exception: java.lang.IllegalArgumentException
Parameter specified as non-null is null: method z.i.a.o.f.c.c.g.onMenuOpened, parameter p1
com.datadog.android.rum.internal.instrumentation.gestures.WindowCallbackWrapper.onMenuOpened
```
```
com.datadog.android.rum.internal.instrumentation.gestures.WindowCallbackWrapper.onMenuOpened (WindowCallbackWrapper.java:2)
androidx.appcompat.view.WindowCallbackWrapper.onMenuOpened (WindowCallbackWrapper.java:104)
androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onMenuOpened (AppCompatDelegateImpl.java:2868)
androidx.appcompat.view.WindowCallbackWrapper.onMenuOpened (WindowCallbackWrapper.java:104)
androidx.appcompat.app.ToolbarActionBar$ActionMenuPresenterCallback.onOpenSubMenu (ToolbarActionBar.java:560)
androidx.appcompat.view.menu.BaseMenuPresenter.onSubMenuSelected (BaseMenuPresenter.java:221)
androidx.appcompat.widget.ActionMenuPresenter.showOverflowMenu (ActionMenuPresenter.java:345)
androidx.appcompat.widget.ActionMenuPresenter$OverflowMenuButton.performClick (ActionMenuPresenter.java:681)
android.view.View.performClickInternal (View.java:8147)
android.view.View.access$3700 (View.java:888)
android.view.View$PerformClick.run (View.java:30233)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8414)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```
 - Android OS version:11
 - Device Model:Galaxy S20+
 - Datadog SDK version:1.6.1

**Comment by xgouchet** [comment] 2021-01-02 14:23
Hello @MohammadRezaei92 and thanks for submitting this issue. We'll investigate this crash ASAP. Do you have any additional details on when the problem is happening ? Apparently it's because of one of the menus in your application, could you share with us the XML file or code snippet you use to populate those menus ?

**Comment by MohammadRezaei92** [comment] 2021-01-02 19:37
> Hello @MohammadRezaei92 and thanks for submitting this issue. We'll investigate this crash ASAP. Do you have any additional details on when the problem is happening ? Apparently it's because of one of the menus in your application, could you share with us the XML file or code snippet you use to populate those menus ?

It happens when an overflow menu going to open
```
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">
    <item
        android:id="@+id/action_help"
        android:icon="@drawable/ic_baseline_help_24"
        android:orderInCategory="98"
        android:title="@string/help"
        app:showAsAction="ifRoom" />
    <item
        android:id="@+id/action_later"
        android:orderInCategory="99"
        android:title="@string/later"
        app:showAsAction="never" />
    <item
        android:id="@+id/action_logout"
        android:orderInCategory="100"
        android:title="@string/logout_from_account"
        app:showAsAction="never" />
</menu>
```

**Comment by xgouchet** [comment] 2021-01-04 09:55
Hello @MohammadRezaei92 
I can't seem to reproduce the issue with the menu you sent. Do you have a more complete sample code we could use to understand the issue ?

**Comment by xgouchet** [comment] 2021-02-01 10:51
Hello @MohammadRezaei92 , without any more info we can't work on this issue. I'm closing it now but feel free to repoen it with more information.

**Closed by xgouchet** 2021-02-01 10:51 UTC
Labels: bug

**Comment by hs-kdhillon** [comment] 2021-02-04 18:52
@xgouchet suggestion to reopen the issue in light of the following crashes on an `overflow-menu` in the project:
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p1
at com.datadog.android.rum.internal.instrumentation.gestures.WindowCallbackWrapper.onMenuOpened(Unknown Source:2)
at androidx.appcompat.view.WindowCallbackWrapper.onMenuOpened(WindowCallbackWrapper.java:104)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onMenuOpened(AppCompatDelegateImpl.java:2868)
at com.uxcam.a.d.onMenuOpened(Unknown Source:2)
at androidx.appcompat.app.AppCompatDelegateImpl$ActionMenuPresenterCallback.onOpenSubMenu(AppCompatDelegateImpl.java:2528)
at androidx.appcompat.view.menu.BaseMenuPresenter.onSubMenuSelected(BaseMenuPresenter.java:221)
at androidx.appcompat.widget.ActionMenuPresenter.showOverflowMenu(ActionMenuPresenter.java:345)
at androidx.appcompat.widget.ActionMenuPresenter$OverflowMenuButton.performClick(ActionMenuPresenter.java:681)
at android.view.View.performClickInternal(View.java:7831)
at android.view.View.access$3600(View.java:879)
at android.view.View$PerformClick.run(View.java:29359)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by Meenu1401** [comment] 2022-04-04 06:46
@xgouchet Facing ANR due to DataDog. Please resolve this. 

**SDK version**: 1.10.0
**Android OS version** : 11
**Device** : realme narzo 50A


<img width="1261" alt="Screenshot 2022-04-04 at 12 13 05 PM" src="https://user-images.githubusercontent.com/14975590/161487690-a15010aa-480a-4917-8ce3-fcdabed55802.png">

**Comment by xgouchet** [comment] 2022-04-04 07:25
Hi @Meenu1401 , the issue you're reporting is different from the one on this thread, can you post a new issue. We're going to look into this, but although our SDK do appear to be in this stack, we're calling a method that shouldn't be blocking. The root cause of the ANR seems to be deeper, in the Android Framework, as something might be blocking the vertical sync of the display, hence causing an ANR.
