### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by alparp27** [DataDog/dd-sdk-android#154] opened 2020-02-26 22:22 UTC
**Describe what happened**

From crashlytics there are multiple instances of crashes
```
Fatal Exception: java.lang.InternalError Thread starting during runtime shutdown 
  | java.lang.Thread.nativeCreate (Thread.java)
  | java.lang.Thread.start + 733 (Thread.java:733)
  | okio.AsyncTimeout.scheduleTimeout + 88 (AsyncTimeout.java:88)
  | okio.AsyncTimeout.enter + 80 (AsyncTimeout.java:80)
  | okhttp3.RealCall.execute + 88 (RealCall.java:88)
  | com.datadog.android.core.internal.net.DataOkHttpUploader.upload + 47 (DataOkHttpUploader.kt:47)
  | com.datadog.android.core.internal.data.upload.DataUploadRunnable.consumeBatch + 75 (DataUploadRunnable.kt:75)
  | com.datadog.android.core.internal.data.upload.DataUploadRunnable.run + 39 (DataUploadRunnable.kt:39)
  | android.os.Handler.handleCallback + 790 (Handler.java:790)
  | android.os.HandlerThread.run + 65 (HandlerThread.java:65)
```

**Steps to reproduce the issue:**
Hard to reproduce, I kept running my app doing what app does and it crashes at some point

**Describe what you expected:**
I have recently integrated this into my app, largely java based code.  I followed the steps and I think I did not miss anything but please let me know if I did.

**Additional context**
Out of 115 crashes
Devices
samsung49%
LGE23%
motorola11%
ZTE10%
Other…7%
Operating Systems
7 57%
9 23%
10 12%
8 8%

 - Datadog SDK version: 1.2.1
 - okhttp:3.12.0
- retrofit2:retrofit:2.2.0
 - Proguard configuration: 
implementation ('com.datadoghq:dd-sdk-android:1.2.1') {
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }

**Comment by xgouchet** [comment] 2020-02-28 07:12
Hello and thanks for reporting this issue. 
Can you give us more information on your application setup, namely: 
 - the list of dependencies included in your application
 - the order in which you initialise those dependencies (including Datadog)

**Comment by alparp27** [comment] 2020-02-28 17:11
Please note that data dog is being initialized at very beginning of onCreate of the application and next is Crashlytics.

I have mentioned few dependencies above, would you please mention if you are looking for specific one?  It is not possible for me to copy paste all dependencies or order of initialization.

**Comment by alparp27** [comment] 2020-03-03 23:39
Thank you so much for quick response!

**Comment by xgouchet** [comment] 2020-03-04 09:29
This crash should be fixed in version [`1.3.0`](https://github.com/DataDog/dd-sdk-android/releases/tag/1.3.0).
@alparp27  thanks again for raising this issue

**Closed by xgouchet** 2020-03-04 09:29 UTC
Labels: bug

**Comment by XyrizTan** [comment] 2021-03-26 12:19
@xgouchet Hello, been running to an issue in 1.8.1 where our JUnit tests aren't finishing correctly, looking at the running threads in the stuck test, "datadog_shutdown" thread is present and interrupting it would let the test finish correctly. Any advice?

**Comment by xgouchet** [comment] 2021-03-26 12:26
Hi @XyrizTan, can you share one of the test you're running that have this issue? Are those Unit Tests ran on the JVM (maybe with Robolectric or Unmock), or instrumented tests ran in an emulator?

**Comment by XyrizTan** [comment] 2021-03-26 12:53
@xgouchet Hello, it's a AndroidJUnit4 test assisted with Mockk, when I debugged the test, since the test is involving some static mock of an object that holds an application context, the line of code for Datadog initialisation has been ran (we init Datadog in our application class). If the datadog init line isn't called, the test completes successfully.

**Comment by xgouchet** [comment] 2021-04-12 06:36
Hi @XyrizTan 
Sorry for the late reply, in theory unit tests ran in the JVM should not use the AndroidJUnit4 test, as the Datadog library expects a fully functional Android context, and not a mock. We might look into this in the future, but to do so we would need a complete sample to understand you test setup in order to reproduce this issue on our end.
