### ISSUE TITLE
Please move off bintray/jcenter and onto maven central

### ISSUE THREAD

**Issue by kenyee** [DataDog/dd-sdk-android#561] opened 2021-04-12 17:08 UTC
bintray is a dumpster fire again today (returning cryptic auth errors)...please move the Android SDK onto maven central.
jcenter/bintray is getting shut down within a year anyways...

**Comment by samandmoore** [comment] 2021-04-12 18:31
The issue is related to the bintray / jcenter brown-outs they're doing today

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

>  April 12th, 26th, 2021 | We will have some short service brown-outs to remind users about the services that are going away on May 1st. (Specific hours will be advertised in the Bintray status page.)

Is there any way to help out here?

**Comment by martymiller** [comment] 2021-04-12 18:40
this is a problem.  my builds are failing.

**Comment by kenyee** [comment] 2021-04-12 18:58
Thanks...also noticed that your alpha builds are already on maven central.  Any way we could get the latest released SDK on maven central as well since we have a policy of avoiding alpha/beta SDKs in our builds as much as possible?

**Comment by erawhctim** [comment] 2021-04-13 13:50
Duplicate of #494

**Comment by xgouchet** [comment] 2021-04-13 18:48
Hi @kenyee , @samandmoore, @erawhctim 
The latest stable version `1.8.1` is now available on Maven Central

**Closed by xgouchet** 2021-04-13 18:48 UTC
Labels: enhancement
