### ISSUE TITLE
application_start action event won't be called when AddLongTask event triggered as a first RUM event

### ISSUE THREAD

**Issue by ken-kentan** [DataDog/dd-sdk-android#1582] opened 2023-08-22 08:25 UTC
**Describe what happened**

Usually Datadog will trigger `application_start` action event at first.
But when `AddLongTask` event was triggered as a first RUM event, `application_start` action event won't be triggered.

**Steps to reproduce the issue:**

Trigger any `AddLongTask` quickly when just Datadog initialized.

Sample: https://github.com/ken-kentan/dd-sdk-android/pull/2

**Describe what you expected:**

`application_start` action event should be triggered even if the first RUM event was `AddLongTask`.

I investigated around `RumSessionScope` and found than when `AddLongTask` event was triggered as a first event, `sessionState` was changed to `State.EXPIRED`, then `RumSessionScope::handleEvent` passed `noOpWriter` as an `actualWriter` for `ApplicationStarted` event.
I guess `sessionState` shouldn't be `State.EXPIRED` in this case.

**Additional context**
 - Android OS version: N/A
 - Device Model: N/A
 - Datadog SDK version: 1.19.0-2.0.0
 - Versions of any other relevant dependencies (OkHttp, …):  N/A
 - Proguard configuration: N/A
 - Gradle Plugins: N/A

Note: This issue might be same with https://github.com/DataDog/dd-sdk-android/issues/1523

**Comment by jonathanmos** [comment] 2023-08-22 09:29
Thanks for reporting this. We'll look into it and try to ascertain what's going on here

**Comment by ken-kentan** [comment] 2023-08-29 02:32
@jonathanmos Hi, thank you for taking a look.
We are currently experiencing an issue that can't measure app startup performance due to this issue.
So we would appreciate if we could know the current situation about your investigation.
Please let me know if you need any additional information for this.

**Comment by 0xnm** [comment] 2023-08-29 15:14
Hi @ken-kentan! Thanks for reporting this issue. We've found the root cause and fix is ready in #1591, once merged it should be available in the next 2.x release.

**Comment by ken-kentan** [comment] 2023-08-31 01:47
Thank you for finding the root cause and working on fix! I'm looking forward to get the new version 👍

**Closed** 2023-08-31 08:19 UTC
Labels: bug

**Comment by 0xnm** [comment] 2023-09-07 10:09
Fix is now released in version [2.1.0](https://github.com/DataDog/dd-sdk-android/releases/tag/2.1.0), please check it out and let us know if you have any issues / anomalies.
